const tintColorLight = 'indigo';
const tintColorDark = 'indigo';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    buttonText: '#ffffff',
    buttonBackground: tintColorLight,
    buttonColor: '#4B0082',
    titleColor: '#333',
    warning: '#FEF3C7',
    warningText: '#92400E',
    primary: '#6200ee',
    primaryColor: '#6200ee',
    dangerColor: '#B00020',
    itemBorderColor: 'indigo',
    itemTextColor: '#11181C',
    logoutButtonColor: 'indigo',
    logoutButtonTextColor: '#FFFFFF',
    inputBackground: '#F0F0F0',
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: 'white',
    buttonText: '#ffffff',
    buttonBackground: tintColorDark,
    buttonColor: '#8A2BE2',
    titleColor: '#fff',
    warning: '#FEF3C7',
    warningText: '#92400E',
    primary: '#bb86fc',
    primaryColor: '#bb86fc',
    dangerColor: '#CF6679',
    itemBorderColor: 'indigo',
    itemTextColor: '#ECEDEE',
    logoutButtonColor: 'indigo',
    logoutButtonTextColor: '#FFFFFF',
    inputBackground: '#2F2F2F',
  },
};
